name: GymApp
options:
  bundleIdPrefix: is.pluto
  deploymentTarget:
    iOS: "17.0"
targets:
  GymApp:
    type: application
    platform: iOS
    sources:
      - Sources
    scheme: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: is.pluto.gymapp
        MARKETING_VERSION: "0.1"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Gym
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        CODE_SIGNING_ALLOWED: NO
